/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type HouseholdInvitationTransformer from '#transformers/household_invitation_transformer'
import type HouseholdMemberTransformer from '#transformers/household_member_transformer'
import type HouseholdMembershipTransformer from '#transformers/household_membership_transformer'
import type HouseholdTransformer from '#transformers/household_transformer'
import type MealTypeTransformer from '#transformers/meal_type_transformer'
import type PlannedMealTransformer from '#transformers/planned_meal_transformer'
import type ProductReferenceTransformer from '#transformers/product_reference_transformer'
import type ProductTransformer from '#transformers/product_transformer'
import type RecipeIngredientTransformer from '#transformers/recipe_ingredient_transformer'
import type RecipeTransformer from '#transformers/recipe_transformer'
import type StockItemTransformer from '#transformers/stock_item_transformer'
import type StockMovementTransformer from '#transformers/stock_movement_transformer'
import type StorageLocationTransformer from '#transformers/storage_location_transformer'
import type UserTransformer from '#transformers/user_transformer'

export namespace Data {
  export type HouseholdInvitation = InferData<HouseholdInvitationTransformer>
  export namespace HouseholdInvitation {
    export type Variants = InferVariants<HouseholdInvitationTransformer>
  }
  export type HouseholdMember = InferData<HouseholdMemberTransformer>
  export namespace HouseholdMember {
    export type Variants = InferVariants<HouseholdMemberTransformer>
  }
  export type HouseholdMembership = InferData<HouseholdMembershipTransformer>
  export namespace HouseholdMembership {
    export type Variants = InferVariants<HouseholdMembershipTransformer>
  }
  export type Household = InferData<HouseholdTransformer>
  export namespace Household {
    export type Variants = InferVariants<HouseholdTransformer>
  }
  export type MealType = InferData<MealTypeTransformer>
  export namespace MealType {
    export type Variants = InferVariants<MealTypeTransformer>
  }
  export type PlannedMeal = InferData<PlannedMealTransformer>
  export namespace PlannedMeal {
    export type Variants = InferVariants<PlannedMealTransformer>
  }
  export type ProductReference = InferData<ProductReferenceTransformer>
  export namespace ProductReference {
    export type Variants = InferVariants<ProductReferenceTransformer>
  }
  export type Product = InferData<ProductTransformer>
  export namespace Product {
    export type Variants = InferVariants<ProductTransformer>
  }
  export type RecipeIngredient = InferData<RecipeIngredientTransformer>
  export namespace RecipeIngredient {
    export type Variants = InferVariants<RecipeIngredientTransformer>
  }
  export type Recipe = InferData<RecipeTransformer>
  export namespace Recipe {
    export type Variants = InferVariants<RecipeTransformer>
  }
  export type StockItem = InferData<StockItemTransformer>
  export namespace StockItem {
    export type Variants = InferVariants<StockItemTransformer>
  }
  export type StockMovement = InferData<StockMovementTransformer>
  export namespace StockMovement {
    export type Variants = InferVariants<StockMovementTransformer>
  }
  export type StorageLocation = InferData<StorageLocationTransformer>
  export namespace StorageLocation {
    export type Variants = InferVariants<StorageLocationTransformer>
  }
  export type User = InferData<UserTransformer>
  export namespace User {
    export type Variants = InferVariants<UserTransformer>
  }
}
