/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class ActivityLogSchema extends BaseModel {
  static $columns = ['action', 'createdAt', 'data', 'householdId', 'id', 'subjectId', 'subjectType', 'userId'] as const
  $columns = ActivityLogSchema.$columns
  @column()
  declare action: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare data: any
  @column()
  declare householdId: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare subjectId: string | null
  @column()
  declare subjectType: string | null
  @column()
  declare userId: string | null
}

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class HouseholdInvitationSchema extends BaseModel {
  static $columns = ['code', 'createdAt', 'createdBy', 'expiresAt', 'householdId', 'id', 'revokedAt', 'role', 'updatedAt'] as const
  $columns = HouseholdInvitationSchema.$columns
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdBy: string | null
  @column.dateTime()
  declare expiresAt: DateTime
  @column()
  declare householdId: string
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare revokedAt: DateTime | null
  @column()
  declare role: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class HouseholdMemberSchema extends BaseModel {
  static $columns = ['createdAt', 'householdId', 'id', 'role', 'updatedAt', 'userId'] as const
  $columns = HouseholdMemberSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare householdId: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare role: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}

export class HouseholdSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'settings', 'updatedAt'] as const
  $columns = HouseholdSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare settings: any
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class IngredientSubstituteSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'productId', 'recipeIngredientId'] as const
  $columns = IngredientSubstituteSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare productId: string
  @column()
  declare recipeIngredientId: string
}

export class MealTypeSchema extends BaseModel {
  static $columns = ['createdAt', 'defaultTime', 'householdId', 'id', 'name', 'position', 'updatedAt'] as const
  $columns = MealTypeSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare defaultTime: string
  @column()
  declare householdId: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare position: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ProductReferenceSchema extends BaseModel {
  static $columns = ['barcode', 'brand', 'createdAt', 'id', 'imageUrl', 'name', 'nutritionPer100', 'packageQuantity', 'packageUnit', 'productId', 'shelfLifeDays', 'source', 'updatedAt'] as const
  $columns = ProductReferenceSchema.$columns
  @column()
  declare barcode: string | null
  @column()
  declare brand: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare imageUrl: string | null
  @column()
  declare name: string
  @column()
  declare nutritionPer100: any | null
  @column()
  declare packageQuantity: number | null
  @column()
  declare packageUnit: string | null
  @column()
  declare productId: string
  @column()
  declare shelfLifeDays: number | null
  @column()
  declare source: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ProductSchema extends BaseModel {
  static $columns = ['allergens', 'category', 'ciqualCode', 'createdAt', 'defaultUnit', 'densityGPerMl', 'householdId', 'id', 'name', 'nutritionPer100', 'unitWeightGrams', 'updatedAt'] as const
  $columns = ProductSchema.$columns
  @column()
  declare allergens: any
  @column()
  declare category: string | null
  @column()
  declare ciqualCode: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare defaultUnit: string
  @column()
  declare densityGPerMl: number | null
  @column()
  declare householdId: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare nutritionPer100: any | null
  @column()
  declare unitWeightGrams: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class RecipeIngredientSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'note', 'optional', 'position', 'productId', 'quantity', 'recipeId', 'unit', 'updatedAt'] as const
  $columns = RecipeIngredientSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare note: string | null
  @column()
  declare optional: boolean
  @column()
  declare position: number
  @column()
  declare productId: string
  @column()
  declare quantity: number
  @column()
  declare recipeId: string
  @column()
  declare unit: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class RecipeSchema extends BaseModel {
  static $columns = ['cookMinutes', 'createdAt', 'deletedAt', 'description', 'householdId', 'id', 'imageUrl', 'name', 'prepMinutes', 'servings', 'steps', 'tags', 'updatedAt'] as const
  $columns = RecipeSchema.$columns
  @column()
  declare cookMinutes: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare description: string | null
  @column()
  declare householdId: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare imageUrl: string | null
  @column()
  declare name: string
  @column()
  declare prepMinutes: number | null
  @column()
  declare servings: number
  @column()
  declare steps: any
  @column()
  declare tags: any
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class StockItemSchema extends BaseModel {
  static $columns = ['addedAt', 'createdAt', 'expiresAt', 'householdId', 'id', 'productId', 'productReferenceId', 'quantity', 'status', 'storageLocationId', 'unit', 'updatedAt', 'version'] as const
  $columns = StockItemSchema.$columns
  @column.dateTime()
  declare addedAt: DateTime
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare expiresAt: DateTime | null
  @column()
  declare householdId: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare productId: string
  @column()
  declare productReferenceId: string | null
  @column()
  declare quantity: number
  @column()
  declare status: string
  @column()
  declare storageLocationId: string | null
  @column()
  declare unit: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare version: number
}

export class StockMovementSchema extends BaseModel {
  static $columns = ['context', 'createdAt', 'householdId', 'id', 'quantityDelta', 'stockItemId', 'type', 'unit', 'userId'] as const
  $columns = StockMovementSchema.$columns
  @column()
  declare context: any
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare householdId: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare quantityDelta: number
  @column()
  declare stockItemId: string
  @column()
  declare type: string
  @column()
  declare unit: string
  @column()
  declare userId: string | null
}

export class StorageLocationSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'householdId', 'id', 'name', 'position', 'type', 'updatedAt'] as const
  $columns = StorageLocationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column()
  declare householdId: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare position: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: string
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
